# Generated by Django 5.1.2 on 2024-10-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descriptions', models.TextField(max_length=300, verbose_name='Descripoción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('url_image', models.URLField(blank=True, null=True, verbose_name='Url de la imagen')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Logo del Producto')),
            ],
        ),
    ]
