# Generated by Django 5.1.2 on 2024-11-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_avilable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creacion'),
        ),
    ]
