# Generated by Django 5.1.2 on 2024-10-29 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
                ('biography', models.TextField(verbose_name=500)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boks.author')),
            ],
        ),
    ]
