# Generated by Django 5.1.3 on 2024-11-18 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
                ('status', models.CharField(choices=[('pl', 'Planificacion'), ('ed', 'En desarrollo'), ('pa', 'En pausa'), ('fi', 'Finalizado'), ('ca', 'cancelado')], default='pl', max_length=2)),
                ('start_date', models.DateField(blank=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha aproximada de terminacion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
                ('done', models.BooleanField(default=False, verbose_name='Completado')),
                ('limit_date', models.DateField(blank=True, null=True, verbose_name='Fecha limite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.project', verbose_name='proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado')),
            ],
        ),
    ]
